// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.ui.main.hunt;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import io.android.fanito_androidclient.data.DataManager;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class HuntViewModel_Factory implements Factory<HuntViewModel> {
  private final Provider<DataManager> dataManagerProvider;

  public HuntViewModel_Factory(Provider<DataManager> dataManagerProvider) {
    this.dataManagerProvider = dataManagerProvider;
  }

  @Override
  public HuntViewModel get() {
    return newInstance(dataManagerProvider.get());
  }

  public static HuntViewModel_Factory create(Provider<DataManager> dataManagerProvider) {
    return new HuntViewModel_Factory(dataManagerProvider);
  }

  public static HuntViewModel newInstance(DataManager dataManager) {
    return new HuntViewModel(dataManager);
  }
}
