// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.ui.main.wallet;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import io.android.fanito_androidclient.data.DataManager;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class WalletViewModel_Factory implements Factory<WalletViewModel> {
  private final Provider<DataManager> dataManagerProvider;

  public WalletViewModel_Factory(Provider<DataManager> dataManagerProvider) {
    this.dataManagerProvider = dataManagerProvider;
  }

  @Override
  public WalletViewModel get() {
    return newInstance(dataManagerProvider.get());
  }

  public static WalletViewModel_Factory create(Provider<DataManager> dataManagerProvider) {
    return new WalletViewModel_Factory(dataManagerProvider);
  }

  public static WalletViewModel newInstance(DataManager dataManager) {
    return new WalletViewModel(dataManager);
  }
}
