// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.ui.sample.dialog;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import io.android.fanito_androidclient.data.DataManager;
import io.android.fanito_androidclient.ui.sample.dialog.SampleBottomSheetDialogViewModel;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class SampleBottomSheetDialogViewModel_Factory implements Factory<SampleBottomSheetDialogViewModel> {
  private final Provider<DataManager> dataManagerProvider;

  public SampleBottomSheetDialogViewModel_Factory(Provider<DataManager> dataManagerProvider) {
    this.dataManagerProvider = dataManagerProvider;
  }

  @Override
  public SampleBottomSheetDialogViewModel get() {
    return newInstance(dataManagerProvider.get());
  }

  public static SampleBottomSheetDialogViewModel_Factory create(
      Provider<DataManager> dataManagerProvider) {
    return new SampleBottomSheetDialogViewModel_Factory(dataManagerProvider);
  }

  public static SampleBottomSheetDialogViewModel newInstance(DataManager dataManager) {
    return new SampleBottomSheetDialogViewModel(dataManager);
  }
}
