// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.ui.intro.login;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import io.fanito.android.data.DataManager;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class LoginViewModel_Factory implements Factory<LoginViewModel> {
  private final Provider<DataManager> dataManagerProvider;

  public LoginViewModel_Factory(Provider<DataManager> dataManagerProvider) {
    this.dataManagerProvider = dataManagerProvider;
  }

  @Override
  public LoginViewModel get() {
    return newInstance(dataManagerProvider.get());
  }

  public static LoginViewModel_Factory create(Provider<DataManager> dataManagerProvider) {
    return new LoginViewModel_Factory(dataManagerProvider);
  }

  public static LoginViewModel newInstance(DataManager dataManager) {
    return new LoginViewModel(dataManager);
  }
}
