// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.ui.main.surveys;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import io.android.fanito_androidclient.data.DataManager;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class SurveysViewModel_Factory implements Factory<SurveysViewModel> {
  private final Provider<DataManager> dataManagerProvider;

  public SurveysViewModel_Factory(Provider<DataManager> dataManagerProvider) {
    this.dataManagerProvider = dataManagerProvider;
  }

  @Override
  public SurveysViewModel get() {
    return newInstance(dataManagerProvider.get());
  }

  public static SurveysViewModel_Factory create(Provider<DataManager> dataManagerProvider) {
    return new SurveysViewModel_Factory(dataManagerProvider);
  }

  public static SurveysViewModel newInstance(DataManager dataManager) {
    return new SurveysViewModel(dataManager);
  }
}
