// Generated by Dagger (https://dagger.dev).
package io.fanito.android.ui.splash;

import dagger.MembersInjector;
import dagger.internal.DaggerGenerated;
import dagger.internal.InjectedFieldSignature;
import io.fanito.android.data.local.prefs.AppPreferencesHelper;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class SplashActivity_MembersInjector implements MembersInjector<SplashActivity> {
  private final Provider<AppPreferencesHelper> sharedPrefsProvider;

  public SplashActivity_MembersInjector(Provider<AppPreferencesHelper> sharedPrefsProvider) {
    this.sharedPrefsProvider = sharedPrefsProvider;
  }

  public static MembersInjector<SplashActivity> create(
      Provider<AppPreferencesHelper> sharedPrefsProvider) {
    return new SplashActivity_MembersInjector(sharedPrefsProvider);
  }

  @Override
  public void injectMembers(SplashActivity instance) {
    injectSharedPrefs(instance, sharedPrefsProvider.get());
  }

  @InjectedFieldSignature("io.fanito.android.ui.splash.SplashActivity.sharedPrefs")
  public static void injectSharedPrefs(SplashActivity instance, AppPreferencesHelper sharedPrefs) {
    instance.sharedPrefs = sharedPrefs;
  }
}
