// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.ui.main;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import io.android.fanito_androidclient.data.DataManager;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class MainViewModel_Factory implements Factory<MainViewModel> {
  private final Provider<DataManager> dataManagerProvider;

  public MainViewModel_Factory(Provider<DataManager> dataManagerProvider) {
    this.dataManagerProvider = dataManagerProvider;
  }

  @Override
  public MainViewModel get() {
    return newInstance(dataManagerProvider.get());
  }

  public static MainViewModel_Factory create(Provider<DataManager> dataManagerProvider) {
    return new MainViewModel_Factory(dataManagerProvider);
  }

  public static MainViewModel newInstance(DataManager dataManager) {
    return new MainViewModel(dataManager);
  }
}
