// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.ui.main.home.token_info;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import io.android.fanito_androidclient.data.DataManager;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class TokenInfoViewModel_Factory implements Factory<TokenInfoViewModel> {
  private final Provider<DataManager> dataManagerProvider;

  public TokenInfoViewModel_Factory(Provider<DataManager> dataManagerProvider) {
    this.dataManagerProvider = dataManagerProvider;
  }

  @Override
  public TokenInfoViewModel get() {
    return newInstance(dataManagerProvider.get());
  }

  public static TokenInfoViewModel_Factory create(Provider<DataManager> dataManagerProvider) {
    return new TokenInfoViewModel_Factory(dataManagerProvider);
  }

  public static TokenInfoViewModel newInstance(DataManager dataManager) {
    return new TokenInfoViewModel(dataManager);
  }
}
