// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.ui.main.news;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import io.android.fanito_androidclient.data.DataManager;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class NewsViewModel_Factory implements Factory<NewsViewModel> {
  private final Provider<DataManager> dataManagerProvider;

  public NewsViewModel_Factory(Provider<DataManager> dataManagerProvider) {
    this.dataManagerProvider = dataManagerProvider;
  }

  @Override
  public NewsViewModel get() {
    return newInstance(dataManagerProvider.get());
  }

  public static NewsViewModel_Factory create(Provider<DataManager> dataManagerProvider) {
    return new NewsViewModel_Factory(dataManagerProvider);
  }

  public static NewsViewModel newInstance(DataManager dataManager) {
    return new NewsViewModel(dataManager);
  }
}
