// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.di;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_ProvidePreferenceNameFactory implements Factory<String> {
  @Override
  public String get() {
    return providePreferenceName();
  }

  public static AppModule_ProvidePreferenceNameFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static String providePreferenceName() {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.providePreferenceName());
  }

  private static final class InstanceHolder {
    private static final AppModule_ProvidePreferenceNameFactory INSTANCE = new AppModule_ProvidePreferenceNameFactory();
  }
}
