// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.di;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import io.android.fanito_androidclient.data.resource.AppResourceHelper;
import io.android.fanito_androidclient.data.resource.ResourceHelper;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_ProvideResourceHelperFactory implements Factory<ResourceHelper> {
  private final Provider<AppResourceHelper> appResourceHelperProvider;

  public AppModule_ProvideResourceHelperFactory(
      Provider<AppResourceHelper> appResourceHelperProvider) {
    this.appResourceHelperProvider = appResourceHelperProvider;
  }

  @Override
  public ResourceHelper get() {
    return provideResourceHelper(appResourceHelperProvider.get());
  }

  public static AppModule_ProvideResourceHelperFactory create(
      Provider<AppResourceHelper> appResourceHelperProvider) {
    return new AppModule_ProvideResourceHelperFactory(appResourceHelperProvider);
  }

  public static ResourceHelper provideResourceHelper(AppResourceHelper appResourceHelper) {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.provideResourceHelper(appResourceHelper));
  }
}
