// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.di;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import io.android.fanito_androidclient.data.remote.ApiHelper;
import io.android.fanito_androidclient.data.remote.AppApiHelper;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_ProvideApiHelperFactory implements Factory<ApiHelper> {
  private final Provider<AppApiHelper> appApiHelperProvider;

  public AppModule_ProvideApiHelperFactory(Provider<AppApiHelper> appApiHelperProvider) {
    this.appApiHelperProvider = appApiHelperProvider;
  }

  @Override
  public ApiHelper get() {
    return provideApiHelper(appApiHelperProvider.get());
  }

  public static AppModule_ProvideApiHelperFactory create(
      Provider<AppApiHelper> appApiHelperProvider) {
    return new AppModule_ProvideApiHelperFactory(appApiHelperProvider);
  }

  public static ApiHelper provideApiHelper(AppApiHelper appApiHelper) {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.provideApiHelper(appApiHelper));
  }
}
