// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.di;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import io.fanito.android.data.local.prefs.AppPreferencesHelper;
import io.fanito.android.data.local.prefs.PreferencesHelper;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class AppModule_ProvidePreferencesHelperFactory implements Factory<PreferencesHelper> {
  private final Provider<AppPreferencesHelper> appPreferencesHelperProvider;

  public AppModule_ProvidePreferencesHelperFactory(
      Provider<AppPreferencesHelper> appPreferencesHelperProvider) {
    this.appPreferencesHelperProvider = appPreferencesHelperProvider;
  }

  @Override
  public PreferencesHelper get() {
    return providePreferencesHelper(appPreferencesHelperProvider.get());
  }

  public static AppModule_ProvidePreferencesHelperFactory create(
      Provider<AppPreferencesHelper> appPreferencesHelperProvider) {
    return new AppModule_ProvidePreferencesHelperFactory(appPreferencesHelperProvider);
  }

  public static PreferencesHelper providePreferencesHelper(
      AppPreferencesHelper appPreferencesHelper) {
    return Preconditions.checkNotNullFromProvides(AppModule.INSTANCE.providePreferencesHelper(appPreferencesHelper));
  }
}
