// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.ui.main.deatil;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import io.android.fanito_androidclient.data.DataManager;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class TokenDetailViewModel_Factory implements Factory<TokenDetailViewModel> {
  private final Provider<DataManager> dataManagerProvider;

  public TokenDetailViewModel_Factory(Provider<DataManager> dataManagerProvider) {
    this.dataManagerProvider = dataManagerProvider;
  }

  @Override
  public TokenDetailViewModel get() {
    return newInstance(dataManagerProvider.get());
  }

  public static TokenDetailViewModel_Factory create(Provider<DataManager> dataManagerProvider) {
    return new TokenDetailViewModel_Factory(dataManagerProvider);
  }

  public static TokenDetailViewModel newInstance(DataManager dataManager) {
    return new TokenDetailViewModel(dataManager);
  }
}
