// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.ui.sample.fragment;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import io.android.fanito_androidclient.data.DataManager;import io.android.fanito_androidclient.ui.sample.fragment.SampleFragmentViewModel;
import javax.inject.Provider;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class SampleFragmentViewModel_Factory implements Factory<SampleFragmentViewModel> {
  private final Provider<DataManager> dataManagerProvider;

  public SampleFragmentViewModel_Factory(Provider<DataManager> dataManagerProvider) {
    this.dataManagerProvider = dataManagerProvider;
  }

  @Override
  public SampleFragmentViewModel get() {
    return newInstance(dataManagerProvider.get());
  }

  public static SampleFragmentViewModel_Factory create(Provider<DataManager> dataManagerProvider) {
    return new SampleFragmentViewModel_Factory(dataManagerProvider);
  }

  public static SampleFragmentViewModel newInstance(DataManager dataManager) {
    return new SampleFragmentViewModel(dataManager);
  }
}
