// Generated by Dagger (https://dagger.dev).
package io.fanito.android.ui.main.surveys.voting;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class VotingViewModel_HiltModules_KeyModule_ProvideFactory implements Factory<String> {
  @Override
  public String get() {
    return provide();
  }

  public static VotingViewModel_HiltModules_KeyModule_ProvideFactory create() {
    return InstanceHolder.INSTANCE;
  }

  public static String provide() {
    return Preconditions.checkNotNullFromProvides(VotingViewModel_HiltModules.KeyModule.provide());
  }

  private static final class InstanceHolder {
    private static final VotingViewModel_HiltModules_KeyModule_ProvideFactory INSTANCE = new VotingViewModel_HiltModules_KeyModule_ProvideFactory();
  }
}
