// Generated by Dagger (https://dagger.dev).
package io.android.fanito_androidclient.ui.main.surveys.voting;

import javax.inject.Provider;

import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import io.android.fanito_androidclient.data.DataManager;

@DaggerGenerated
@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class VotingViewModel_Factory implements Factory<VotingViewModel> {
  private final Provider<DataManager> dataManagerProvider;

  public VotingViewModel_Factory(Provider<DataManager> dataManagerProvider) {
    this.dataManagerProvider = dataManagerProvider;
  }

  @Override
  public VotingViewModel get() {
    return newInstance(dataManagerProvider.get());
  }

  public static VotingViewModel_Factory create(Provider<DataManager> dataManagerProvider) {
    return new VotingViewModel_Factory(dataManagerProvider);
  }

  public static VotingViewModel newInstance(DataManager dataManager) {
    return new VotingViewModel(dataManager);
  }
}
